<?xml version="1.0" encoding="UTF-8"?>

<definitions name="dsservice" targetNamespace="urn:ds" xmlns:tns="urn:ds" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types/>
  <message name="dsint_getvideo">
    <part name="String_1" type="xsd:string"/></message>
  <message name="dsint_getvideoResponse">
    <part name="result" type="xsd:base64Binary"/></message>
  <portType name="dsint">
    <operation name="getvideo" parameterOrder="String_1">
      <input message="tns:dsint_getvideo"/>
      <output message="tns:dsint_getvideoResponse"/></operation></portType>
  <binding name="dsintBinding" type="tns:dsint">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <operation name="getvideo">
      <soap:operation soapAction=""/>
      <input>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="encoded" namespace="urn:ds"/></input>
      <output>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="encoded" namespace="urn:ds"/></output></operation></binding>
  <service name="Dsservice">
    <port name="dsintPort" binding="tns:dsintBinding">
      <soap:address location="REPLACE_WITH_ACTUAL_URL"/></port></service></definitions>
