// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package ds;


public class Dsint_getvideo_RequestStruct {
    protected java.lang.String string_1;
    
    public Dsint_getvideo_RequestStruct() {
    }
    
    public Dsint_getvideo_RequestStruct(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
}
