// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package ds;


public class Dsint_getvideo_ResponseStruct {
    protected byte[] result;
    
    public Dsint_getvideo_ResponseStruct() {
    }
    
    public Dsint_getvideo_ResponseStruct(byte[] result) {
        this.result = result;
    }
    
    public byte[] getResult() {
        return result;
    }
    
    public void setResult(byte[] result) {
        this.result = result;
    }
}
