// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package ds;

public interface Dsint extends java.rmi.Remote {
    public byte[] getvideo(java.lang.String string_1) throws 
         java.rmi.RemoteException;
}
